name: Submit All - Staging

on:
  workflow_dispatch:
    inputs:
      pr-number:
        description: 'PR to run against'
        required: true

jobs:
  staging:
    uses: ./.github/workflows/reusable.quickstart_submission.yml
    with:
      pr-number: ${{ github.event.inputs.pr-number }}
      dry-run: false
    secrets:
      nr-api-url: ${{ secrets.NR_API_URL_STAGING }}
      nr-api-token: ${{ secrets.NR_API_TOKEN_STAGING }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
